version: '3.7'

services:

    mongodb:
        build:
            context: .
            dockerfile: Dockerfile.mongo
            args:
                BITBUCKET_USERNAME: "${BITBUCKET_USERNAME}"
                BITBUCKET_PASSWORD: "${BITBUCKET_PASSWORD}"
        ports:
            - "27017:27017"

    rabbitmq:
        image: rabbitmq:3.8

    elasticsearch:
        image: elasticsearch:6.4.0
        environment:
            - "transport.host=localhost"

    learning-object-service:
        image: cyber4all/learning-object-service
        environment: 
            - ELASTICSEARCH_DOMAIN=http://elasticsearch:9200
            - CLARK_DB_URI_DEV=mongodb://mongodb:27017/onion
            - AMQP_URL=amqp://rabbitmq:5672
            - ISSUER=THIS_IS_AN_ISSUER
            - KEY=THIS_IS_A_KEY
            - NODE_ENV=development
        restart: always

    user-service:
        image: cyber4all/user-service
        environment: 
            - CLARK_DB_URI_DEV=mongodb://mongodb:27017/onion
            - ISSUER=THIS_IS_AN_ISSUER
            - KEY=THIS_IS_A_KEY
            - NODE_ENV=development
        restart: always

    outcome-service:
        build:
            context: .
            target: builder
        command: ./wait-for-container.sh http://learning-object-service "npm run server-test"
        environment: 
            - DB_URI_ONION=mongodb://mongodb:27017/onion
            - DB_URI_OUTCOMES=mongodb://mongodb:27017/outcomes
        ports:
            - "3000:3000"
        
volumes:
    notused:
