version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
    build:
        executor:
            name: node/default
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Build Image
                command: | 
                    docker build -t outcome-service:$CIRCLE_SHA1 .
    run-functional-tests:
        executor:
            name: node/default
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Clone database image
                command: git clone https://$BITBUCKET_USERNAME:$BITBUCKET_PASSWORD@bitbucket.org/cyber4all-clark/database-image.git
            - run:
                name: debug
                command: ls
            # - run:
            #     name: Run Functional Test Suite
            #     command: | 
            #         docker-compose -f docker-compose.functional-tests.yml up

workflows:
    build-and-test:
      jobs:
        - build
        - run-functional-tests:
            requires:
                - build